name: ElyTools
version: '1.0-SNAPSHOT'
main: me.wertiko.elyTools.ElyTools
api-version: '1.21'

commands:
  size:
    description: Edit self size
  description:
    description: Toggle self desc
  elytools:
    description: Reload configuration

permissions:
  elytools.description:
    default: op
  elytools.size:
    default: op
  elytools.reload:
    default: op
